# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Nbcat < Formula
  include Language::Python::Virtualenv

  desc "Preview jupyter notebooks directly in your terminal think of it as cat, but for"
  homepage "https://github.com/akopdev/nbcat"
  url "https://github.com/akopdev/nbcat/archive/refs/tags/v0.10.0.tar.gz"
  version "0.10.0"
  sha256 "9f9d6458cf64e61cc3f824e968e999fb91998bfe6de8bc56f2e1f90796cf085d"
  license "MIT"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nbcat --version")
  end
end
