name: ci

on: [push, pull_request]

jobs:
  tap:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew tap akopdev/formulas
  install:
    runs-on: macos-latest
    needs: tap
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: |
          brew developer on
          for formula in Formula/*.rb; do
            echo "::group::Installing and testing $(basename "$formula")"
            brew install --build-from-source "$formula"
            brew test --verbose "$formula" || exit 1
            echo "::endgroup::"
          done
  audit:
    runs-on: macos-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew audit --tap akopdev/formulas
